// <auto-generated />
using System;
using Lagerverwaltung.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lagerverwaltung.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526065411_AddRequestCatalogItems")]
    partial class AddRequestCatalogItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LAGERVERWALTUNG")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Approver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<int>("IsActiveValue")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_APPROVER_EMAIL_N");

                    b.ToTable("Approver", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MinimumAmount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NeedsNotificationValue")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("NeedsNotification");

                    b.Property<string>("RestockEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)")
                        .HasColumnName("RESTOCK_EMAIL");

                    b.HasKey("ID");

                    b.ToTable("Categories", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Deleted", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.ToTable("Deleted", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Destroyed", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DestroyDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PositionID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PositionOrderNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.ToTable("Destroyeds", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproveToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("APPROVE_TOKEN");

                    b.Property<string>("BossComment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DenyToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DENY_TOKEN");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("FulfillmentDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FULFILLMENT_DATE");

                    b.Property<int?>("FulfillmentType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FULFILLMENT_TYPE");

                    b.Property<int>("PositionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SupervisorEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SUPERVISOR_EMAIL");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SUPERVISOR_NAME");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TICKET_NUMBER");

                    b.Property<int>("UsedItemOkValue")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("USED_ITEM_OK");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_EQREQ_TICKET");

                    b.ToTable("EquipmentRequests", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PositionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("TakeBackDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("PositionId");

                    b.ToTable("Issue", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.LowStockNotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableAmount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AVAILABLE_AMOUNT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int>("MinimumAmount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MINIMUM_AMOUNT");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)")
                        .HasColumnName("RECIPIENT_EMAIL");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SENT_AT");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TRIGGER_REASON");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "SentAt")
                        .HasDatabaseName("IX_LOW_STOCK_CAT_SENT");

                    b.ToTable("LOW_STOCK_NOTIFICATION_LOGS", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Price")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("StockCondition")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK_CONDITION");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Positions", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.RequestCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ACTION_CODE");

                    b.Property<string>("BillingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BILLING_TYPE");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CURRENCY");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FULFILLMENT_MODE");

                    b.Property<int>("IsActiveValue")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("RequiresCommentValue")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REQUIRES_COMMENT");

                    b.Property<int>("ReturnableValue")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RETURNABLE");

                    b.Property<int?>("StorageCategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STORAGE_CATEGORY_ID");

                    b.HasKey("Id");

                    b.HasIndex("ActionCode")
                        .IsUnique()
                        .HasDatabaseName("UX_REQCAT_ACTION");

                    b.HasIndex("StorageCategoryId")
                        .HasDatabaseName("IX_REQCAT_STOR_CAT");

                    b.HasIndex("IsActiveValue", "CategoryName")
                        .HasDatabaseName("IX_REQCAT_ACTIVE_CAT");

                    b.ToTable("REQUEST_CATALOG_ITEMS", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("ADMIN_COMMENT");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONFIRMED_AT");

                    b.Property<int>("EquipmentRequestId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIPMENT_REQUEST_ID");

                    b.Property<int>("PositionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POSITION_ID");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REQUESTED_AT");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)")
                        .HasColumnName("REQUESTER_EMAIL");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("REQUESTER_NAME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("USER_COMMENT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentRequestId")
                        .HasDatabaseName("IX_RETURN_REQ_EQREQ");

                    b.HasIndex("PositionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RETURN_REQ_STATUS");

                    b.ToTable("RETURN_REQUESTS", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Position", null)
                        .WithMany("Issued")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.LowStockNotificationLog", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Category", "Category")
                        .WithMany("Positions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.RequestCatalogItem", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Category", "StorageCategory")
                        .WithMany()
                        .HasForeignKey("StorageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REQCAT_CATEGORY");

                    b.Navigation("StorageCategory");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.ReturnRequest", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.EquipmentRequest", "EquipmentRequest")
                        .WithMany()
                        .HasForeignKey("EquipmentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentRequest");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.Navigation("Issued");
                });
#pragma warning restore 612, 618
        }
    }
}
