// <auto-generated />
using System;
using Lagerverwaltung.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lagerverwaltung.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401143745_AddEquipmentRequestTable")]
    partial class AddEquipmentRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LAGERVERWALTUNG")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MinimumAmount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("NeedsNotification")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("ID");

                    b.ToTable("Categories", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproveToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("APPROVE_TOKEN");

                    b.Property<string>("BossComment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DenyToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DENY_TOKEN");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PositionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("EquipmentRequests", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PositionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("TakeBackDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("PositionId");

                    b.ToTable("Issue", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Price")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Positions", "LAGERVERWALTUNG");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Position", null)
                        .WithMany("Issued")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.HasOne("Lagerverwaltung.Web.Models.Category", "Category")
                        .WithMany("Positions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
                {
                    b.Navigation("Issued");
                });
#pragma warning restore 612, 618
        }
    }
}
