// <auto-generated />
using System;
using Lagerverwaltung.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lagerverwaltung.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609000000_AddSiteCatalogItems")]
    partial class AddSiteCatalogItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LAGERVERWALTUNG")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Approver", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)");

                b.Property<string>("EmailNormalized")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)");

                b.Property<int>("IsActiveValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IsActive");

                b.Property<DateTime?>("LastSyncedAt")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TIMESTAMP(7)");

                b.HasKey("Id");

                b.HasIndex("EmailNormalized")
                    .IsUnique()
                    .HasDatabaseName("UX_APPROVER_EMAIL_N");

                b.ToTable("Approver", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("MinimumAmount")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("NeedsNotificationValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("NeedsNotification");

                b.Property<string>("RestockEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("RESTOCK_EMAIL");

                b.Property<int>("SiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SITE_ID");

                b.HasKey("ID");

                b.HasIndex("SiteId")
                    .HasDatabaseName("IX_CAT_SITE");

                b.ToTable("Categories", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Deleted", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime>("DeletedDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("OrderNumber")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("ID");

                b.ToTable("Deleted", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Destroyed", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime>("DestroyDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<int>("PositionID")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("PositionOrderNumber")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("ID");

                b.ToTable("Destroyeds", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentOrder", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ApproveToken")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("APPROVE_TOKEN");

                b.Property<string>("BossComment")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("BOSS_COMMENT");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("COMPLETED_AT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("CREATED_AT");

                b.Property<DateTime?>("DecisionDate")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("DECISION_DATE");

                b.Property<string>("DenyToken")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("DENY_TOKEN");

                b.Property<string>("OrderedByEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("ORDERED_BY_EMAIL");

                b.Property<string>("OrderedByName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("ORDERED_BY_NAME");

                b.Property<string>("PickupContactEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("PICKUP_CONTACT_EMAIL");

                b.Property<string>("PickupContactName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("PICKUP_CONTACT_NAME");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("REASON");

                b.Property<string>("RequestedForEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("REQUESTED_FOR_EMAIL");

                b.Property<string>("RequestedForName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("REQUESTED_FOR_NAME");

                b.Property<int>("SiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SITE_ID");

                b.Property<int>("Status")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STATUS");

                b.Property<string>("SupervisorEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("SUPERVISOR_EMAIL");

                b.Property<string>("SupervisorName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("SUPERVISOR_NAME");

                b.Property<string>("TicketNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("TICKET_NUMBER");

                b.HasKey("Id");

                b.HasIndex("TicketNumber")
                    .IsUnique()
                    .HasDatabaseName("UX_EQORD_TICKET");

                b.HasIndex("Status", "CreatedAt")
                    .HasDatabaseName("IX_EQORD_STATUS_CREATED");

                b.HasIndex("SiteId", "Status", "CreatedAt")
                    .HasDatabaseName("IX_EQORD_SITE_STATUS");

                b.ToTable("EQUIPMENT_ORDERS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentOrderLine", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActionCode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("ACTION_CODE");

                b.Property<string>("AdminComment")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)")
                    .HasColumnName("ADMIN_COMMENT");

                b.Property<string>("BillingType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("BILLING_TYPE");

                b.Property<int>("CatalogFulfillmentMode")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("CATALOG_FULFILLMENT_MODE");

                b.Property<int>("CatalogItemId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("CATALOG_ITEM_ID");

                b.Property<string>("CategoryName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("CATEGORY_NAME");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("NVARCHAR2(10)")
                    .HasColumnName("CURRENCY");

                b.Property<int>("EffectiveFulfillmentMode")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("EFFECTIVE_FULFILLMENT_MODE");

                b.Property<int>("EquipmentOrderId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("EQUIPMENT_ORDER_ID");

                b.Property<DateTime?>("FulfilledAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("FULFILLED_AT");

                b.Property<string>("ItemName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("ITEM_NAME");

                b.Property<string>("Manufacturer")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("MANUFACTURER");

                b.Property<int?>("PositionId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("POSITION_ID");

                b.Property<int>("Quantity")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("QUANTITY");

                b.Property<int>("ReturnableValue")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("RETURNABLE");

                b.Property<int>("Status")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STATUS");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("NUMBER(18,2)")
                    .HasColumnName("UNIT_PRICE");

                b.Property<int>("UsedItemOkValue")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("USED_ITEM_OK");

                b.Property<string>("UserComment")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)")
                    .HasColumnName("USER_COMMENT");

                b.HasKey("Id");

                b.HasIndex("CatalogItemId")
                    .HasDatabaseName("IX_EQOL_CATALOG");

                b.HasIndex("EquipmentOrderId")
                    .HasDatabaseName("IX_EQOL_ORDER");

                b.HasIndex("PositionId")
                    .HasDatabaseName("IX_EQOL_POSITION");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_EQOL_STATUS");

                b.ToTable("EQUIPMENT_ORDER_LINES", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ApproveToken")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("APPROVE_TOKEN");

                b.Property<string>("BossComment")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime?>("DecisionDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("DenyToken")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("DENY_TOKEN");

                b.Property<string>("Department")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime?>("FulfillmentDate")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("FULFILLMENT_DATE");

                b.Property<int?>("FulfillmentType")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("FULFILLMENT_TYPE");

                b.Property<int>("PositionId")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime>("RequestDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("RequesterEmail")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("RequesterName")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("Status")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("SupervisorEmail")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("SUPERVISOR_EMAIL");

                b.Property<string>("SupervisorName")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)")
                    .HasColumnName("SUPERVISOR_NAME");

                b.Property<string>("TicketNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("TICKET_NUMBER");

                b.Property<int>("UsedItemOkValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("USED_ITEM_OK");

                b.HasKey("Id");

                b.HasIndex("PositionId");

                b.HasIndex("TicketNumber")
                    .IsUnique()
                    .HasDatabaseName("UX_EQREQ_TICKET");

                b.ToTable("EquipmentRequests", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<string>("CostCentre")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<DateTime>("IssueDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<int>("PositionId")
                    .HasColumnType("NUMBER(10)");

                b.Property<DateTime?>("TakeBackDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("TicketNumber")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("ID");

                b.HasIndex("PositionId");

                b.ToTable("Issue", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.LowStockNotificationLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AvailableAmount")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("AVAILABLE_AMOUNT");

                b.Property<int>("CategoryId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("CATEGORY_ID");

                b.Property<int>("MinimumAmount")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("MINIMUM_AMOUNT");

                b.Property<string>("RecipientEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("RECIPIENT_EMAIL");

                b.Property<DateTime>("SentAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("SENT_AT");

                b.Property<string>("TriggerReason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("TRIGGER_REASON");

                b.HasKey("Id");

                b.HasIndex("CategoryId", "SentAt")
                    .HasDatabaseName("IX_LOW_STOCK_CAT_SENT");

                b.ToTable("LOW_STOCK_NOTIFICATION_LOGS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                b.Property<int>("CategoryId")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("OrderNumber")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<double>("Price")
                    .HasColumnType("BINARY_DOUBLE");

                b.Property<DateTime>("PurchaseDate")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<int>("SiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SITE_ID");

                b.Property<int>("StockCondition")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STOCK_CONDITION");

                b.Property<string>("Supplier")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("ID");

                b.HasIndex("CategoryId");

                b.HasIndex("SiteId")
                    .HasDatabaseName("IX_POS_SITE");

                b.HasIndex("SiteId", "CategoryId")
                    .HasDatabaseName("IX_POS_SITE_CAT");

                b.ToTable("Positions", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.RequestCatalogItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActionCode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("ACTION_CODE");

                b.Property<string>("BillingType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("BILLING_TYPE");

                b.Property<string>("CategoryName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("CATEGORY_NAME");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("NVARCHAR2(10)")
                    .HasColumnName("CURRENCY");

                b.Property<int>("FulfillmentMode")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("FULFILLMENT_MODE");

                b.Property<int>("IsActiveValue")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("IS_ACTIVE");

                b.Property<string>("ItemName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("ITEM_NAME");

                b.Property<string>("Manufacturer")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("MANUFACTURER");

                b.Property<decimal>("Price")
                    .HasColumnType("NUMBER(18,2)")
                    .HasColumnName("PRICE");

                b.Property<int>("RequiresCommentValue")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("REQUIRES_COMMENT");

                b.Property<int>("ReturnableValue")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("RETURNABLE");

                b.Property<int?>("StorageCategoryId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STORAGE_CATEGORY_ID");

                b.HasKey("Id");

                b.HasIndex("ActionCode")
                    .IsUnique()
                    .HasDatabaseName("UX_REQCAT_ACTION");

                b.HasIndex("StorageCategoryId")
                    .HasDatabaseName("IX_REQCAT_STOR_CAT");

                b.HasIndex("IsActiveValue", "CategoryName")
                    .HasDatabaseName("IX_REQCAT_ACTIVE_CAT");

                b.ToTable("REQUEST_CATALOG_ITEMS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.ReturnRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AdminComment")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)")
                    .HasColumnName("ADMIN_COMMENT");

                b.Property<DateTime?>("ConfirmedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("CONFIRMED_AT");

                b.Property<int?>("EquipmentOrderLineId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("EQUIPMENT_ORDER_LINE_ID");

                b.Property<int?>("EquipmentRequestId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("EQUIPMENT_REQUEST_ID");

                b.Property<int>("PositionId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("POSITION_ID");

                b.Property<DateTime>("RequestedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("REQUESTED_AT");

                b.Property<string>("RequesterEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("REQUESTER_EMAIL");

                b.Property<string>("RequesterName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("REQUESTER_NAME");

                b.Property<int>("Status")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STATUS");

                b.Property<string>("UserComment")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)")
                    .HasColumnName("USER_COMMENT");

                b.HasKey("Id");

                b.HasIndex("EquipmentOrderLineId")
                    .HasDatabaseName("IX_RETURN_REQ_OLINE");

                b.HasIndex("EquipmentRequestId")
                    .HasDatabaseName("IX_RETURN_REQ_EQREQ");

                b.HasIndex("PositionId");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_RETURN_REQ_STATUS");

                b.ToTable("RETURN_REQUESTS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Site", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AdminCulture")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("ADMIN_CULTURE");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("NVARCHAR2(30)")
                    .HasColumnName("CODE");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("CREATED_AT");

                b.Property<string>("DefaultCulture")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("DEFAULT_CULTURE");

                b.Property<string>("EntraGroupObjectId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("ENTRA_GROUP_ID");

                b.Property<int>("IsActiveValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IS_ACTIVE");

                b.Property<string>("ItEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("IT_EMAIL");

                b.Property<string>("LowStockEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("LOW_STOCK_EMAIL");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("NAME");

                b.Property<int>("StockPolicy")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STOCK_POLICY");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("UPDATED_AT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("UX_SITES_CODE");

                b.ToTable("SITES", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.SiteCatalogItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("BillingTypeOverride")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("BILLING_TYPE_OVERRIDE");

                b.Property<int>("CatalogItemId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("CATALOG_ITEM_ID");

                b.Property<int?>("FulfillmentModeOverride")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("FULFILLMENT_MODE_OVERRIDE");

                b.Property<int>("IsActiveValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IS_ACTIVE");

                b.Property<decimal?>("PriceOverride")
                    .HasColumnType("NUMBER(18,2)")
                    .HasColumnName("PRICE_OVERRIDE");

                b.Property<int>("SiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SITE_ID");

                b.Property<int>("SortOrder")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SORT_ORDER");

                b.Property<int?>("StorageCategoryId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("STORAGE_CATEGORY_ID");

                b.HasKey("Id");

                b.HasIndex("CatalogItemId")
                    .HasDatabaseName("IX_SCAT_CATALOG");

                b.HasIndex("SiteId")
                    .HasDatabaseName("IX_SCAT_SITE");

                b.HasIndex("SiteId", "CatalogItemId")
                    .IsUnique()
                    .HasDatabaseName("UX_SCAT_SITE_CATALOG");

                b.ToTable("SITE_CATALOG_ITEMS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.UserPreference", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("LastSelectedSiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("LAST_SITE_ID");

                b.Property<string>("PreferredCulture")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("PREFERRED_CULTURE");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("UPDATED_AT");

                b.Property<string>("UserEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("USER_EMAIL");

                b.Property<string>("UserEmailNormalized")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("USER_EMAIL_N");

                b.HasKey("Id");

                b.HasIndex("LastSelectedSiteId")
                    .HasDatabaseName("IX_PREF_SITE");

                b.HasIndex("UserEmailNormalized")
                    .IsUnique()
                    .HasDatabaseName("UX_USER_PREF_EMAIL");

                b.ToTable("USER_PREFS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.UserSiteAccess", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CanFulfillValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("CAN_FULFILL");

                b.Property<int>("CanOrderValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("CAN_ORDER");

                b.Property<int>("IsActiveValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IS_ACTIVE");

                b.Property<int>("IsAdminValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IS_ADMIN");

                b.Property<int>("IsDefaultValue")
                    .HasPrecision(1)
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("IS_DEFAULT");

                b.Property<int>("SiteId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("SITE_ID");

                b.Property<string>("UserEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("USER_EMAIL");

                b.Property<string>("UserEmailNormalized")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("NVARCHAR2(320)")
                    .HasColumnName("USER_EMAIL_N");

                b.HasKey("Id");

                b.HasIndex("SiteId")
                    .HasDatabaseName("IX_USA_SITE");

                b.HasIndex("UserEmailNormalized", "SiteId")
                    .IsUnique()
                    .HasDatabaseName("UX_USA_EMAIL_SITE");

                b.ToTable("USER_SITE_ACCESS", "LAGERVERWALTUNG");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Site", "Site")
                    .WithMany("Categories")
                    .HasForeignKey("SiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_CAT_SITE");

                b.Navigation("Site");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentOrder", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Site", "Site")
                    .WithMany()
                    .HasForeignKey("SiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_EQORD_SITE");

                b.Navigation("Site");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentOrderLine", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.RequestCatalogItem", "CatalogItem")
                    .WithMany()
                    .HasForeignKey("CatalogItemId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_EQOL_REQCAT");

                b.HasOne("Lagerverwaltung.Web.Models.EquipmentOrder", "EquipmentOrder")
                    .WithMany("Lines")
                    .HasForeignKey("EquipmentOrderId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_EQOL_ORDER");

                b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                    .WithMany()
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_EQOL_POSITION");

                b.Navigation("CatalogItem");

                b.Navigation("EquipmentOrder");

                b.Navigation("Position");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentRequest", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                    .WithMany()
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Position");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Issue", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Position", null)
                    .WithMany("Issued")
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.LowStockNotificationLog", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Category");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Category", "Category")
                    .WithMany("Positions")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Lagerverwaltung.Web.Models.Site", "Site")
                    .WithMany("Positions")
                    .HasForeignKey("SiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_POS_SITE");

                b.Navigation("Category");

                b.Navigation("Site");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.RequestCatalogItem", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Category", "StorageCategory")
                    .WithMany()
                    .HasForeignKey("StorageCategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_REQCAT_CATEGORY");

                b.Navigation("StorageCategory");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.ReturnRequest", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.EquipmentOrderLine", "EquipmentOrderLine")
                    .WithMany()
                    .HasForeignKey("EquipmentOrderLineId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_RET_ORDER_LINE");

                b.HasOne("Lagerverwaltung.Web.Models.EquipmentRequest", "EquipmentRequest")
                    .WithMany()
                    .HasForeignKey("EquipmentRequestId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Lagerverwaltung.Web.Models.Position", "Position")
                    .WithMany()
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("EquipmentOrderLine");

                b.Navigation("EquipmentRequest");

                b.Navigation("Position");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.SiteCatalogItem", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.RequestCatalogItem", "CatalogItem")
                    .WithMany()
                    .HasForeignKey("CatalogItemId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_SCAT_REQCAT");

                b.HasOne("Lagerverwaltung.Web.Models.Site", "Site")
                    .WithMany()
                    .HasForeignKey("SiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_SCAT_SITE");

                b.HasOne("Lagerverwaltung.Web.Models.Category", "StorageCategory")
                    .WithMany()
                    .HasForeignKey("StorageCategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_SCAT_CATEGORY");

                b.Navigation("CatalogItem");

                b.Navigation("Site");

                b.Navigation("StorageCategory");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.UserPreference", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Site", "LastSelectedSite")
                    .WithMany()
                    .HasForeignKey("LastSelectedSiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_PREF_SITE");

                b.Navigation("LastSelectedSite");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.UserSiteAccess", b =>
            {
                b.HasOne("Lagerverwaltung.Web.Models.Site", "Site")
                    .WithMany()
                    .HasForeignKey("SiteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_USA_SITE");

                b.Navigation("Site");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Category", b =>
            {
                b.Navigation("Positions");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.EquipmentOrder", b =>
            {
                b.Navigation("Lines");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Position", b =>
            {
                b.Navigation("Issued");
            });

            modelBuilder.Entity("Lagerverwaltung.Web.Models.Site", b =>
            {
                b.Navigation("Categories");

                b.Navigation("Positions");
            });
#pragma warning restore 612, 618
        }
    }
}
